In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("job_listings_USA.csv", encoding = "ISO-8859-1",header=None)

In [3]:
df.columns = ['Title','Brand','Category','City','State','Date']

In [4]:
df.shape

(12428859, 6)

In [5]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

In [6]:
df_linkedin = pd.read_csv("temp_datalab_records_linkedin_company.csv")

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [19]:
df_linkedin_clean = df_linkedin.dropna(subset=['industry'])
df_linkedin_clean.groupby('industry')['employees_on_platform'].sum().sort_values(ascending=False)

industry
Information Technology and Services     2383349091
Financial Services                      1701931846
Retail                                  1424502315
Banking                                  961924799
Telecommunications                       925623563
Pharmaceuticals                          645660609
Oil & Energy                             609859377
Internet                                 540464477
Automotive                               531717088
Computer Software                        490204437
Hospital & Health Care                   484030319
Electrical/Electronic Manufacturing      473128390
Consumer Goods                           404053850
Insurance                                350383155
Restaurants                              337532632
Semiconductors                           300664855
Medical Devices                          245134643
Food & Beverages                         225359422
Defense & Space                          222953151
Hospitality                              201140778
Airlines/Aviation                        191821141
Utilities                                185608941
Chemicals                                183490393
Biotechnology                            181504943
Aviation & Aerospace                     166129253
Entertainment                            162897542
Consumer Electronics                     161385791
Mechanical or Industrial Engineering     153855767
Mining & Metals                          144344501
Real Estate                              140182991
                                           ...
Design                                      833980
Public Relations and Communications         779004
Luxury Goods &amp; Jewelry                  619553
Renewables &amp; Environment                612045
Capital Markets                             584829
Motion Pictures and Film                    567750
Glass, Ceramics &amp; Concrete              519664
Shipbuilding                                276514
Venture Capital & Private Equity            252735
Warehousing                                 228894
Gambling &amp; Casinos                      227807
Veterinary                                  227788
Individual &amp; Family Services            217687
Executive Office                            143283
Nanotechnology                              116052
Legal Services                               93232
Professional Training &amp; Coaching         88906
Recreational Facilities and Services         36456
International Trade and Development          30546
Writing and Editing                          17097
Venture Capital &amp; Private Equity         10852
Law Practice                                  9883
Ranching                                      6997
Graphic Design                                4184
Medical Practice                              3166
Market Research                               2987
Nonprofit Organization Management             1863
Program Development                           1335
Military                                         0
Photography                                      0
Name: employees_on_platform, Length: 140, dtype: int64

In [8]:
d_company_industry = dict(df_linkedin_clean.groupby('company_name')['industry'].apply(list))

In [9]:
df['Industry'] = df['Brand'].apply(lambda s: d_company_industry[s][0] if s in d_company_industry else np.nan)
df_temp = df.dropna(subset=['Industry'])
df_temp.shape

(1792219, 7)

In [10]:
df_temp.head()

,Title,Brand,Category,City,State,Date,Industry
0,Automotive Technician Coggin Honda St. Augustine,Asbury Automotive Group,NaN,St. Augustine,FL,2018-04-12,Automotive
1,Part Time Receptionist / Nights and Weekends /...,Asbury Automotive Group,NaN,Atlanta,GA,2018-03-05,Automotive
2,Service Technician & Used Technician McDavid P...,Asbury Automotive Group,NaN,Plano,TX,2018-04-16,Automotive
3,Part-time Receptionist / Plaza Land Rover,Asbury Automotive Group,NaN,Creve Coeur,MO,2018-04-23,Automotive
4,Automotive Service Technician McDavid Honda Ir...,Asbury Automotive Group,NaN,Irving,TX,2018-04-30,Automotive

In [13]:
df_temp['Industry'].value_counts()

Retail                                 685453
Internet                               240642
Business Supplies and Equipment        219109
Consumer Electronics                   205969
Banking                                 50091
Restaurants                             37648
Hospital &amp; Health Care              34668
Apparel & Fashion                       33129
Information Technology and Services     32820
Investment Banking                      31205
Automotive                              23176
Government Administration               19067
Logistics and Supply Chain              18452
Renewables & Environment                18325
Electrical/Electronic Manufacturing     16890
Construction                            16658
Broadcast Media                         13966
Computer Software                       13358
Pharmaceuticals                         10222
Hospital & Health Care                  10017
Machinery                                7406
Research                                 6844
Packaging and Containers                 6306
Biotechnology                            5224
Defense &amp; Space                      4628
Education Management                     4576
Medical Devices                          4211
Building Materials                       4112
Real Estate                              3903
Chemicals                                2548
Entertainment                            1664
Commercial Real Estate                   1643
Financial Services                       1637
Airlines/Aviation                        1449
Semiconductors                           1428
Wireless                                 1341
Insurance                                1294
Utilities                                 515
Oil &amp; Energy                          251
Tobacco                                    84
Outsourcing/Offshoring                     82
Telecommunications                         77
Consumer Goods                             70
Marketing and Advertising                  61
Name: Industry, dtype: int64

In [28]:
def get_part_full(s):
    if s == np.nan:
        return np.nan
    
    if 'Full-Time'.upper() in str(s).upper():
        return 'FULL'
    elif 'Part-Time'.upper() in str(s).upper():
        return 'PART'
    else:
        return np.nan

df_temp['Full/Part'] = df_temp['Category'].apply(lambda s: get_part_full(s))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

In [32]:
df_temp.groupby(['Full/Part','Industry'])['Industry'].count()

Full/Part  Industry
FULL       Business Supplies and Equipment      2962
           Education Management                 1950
           Hospital & Health Care               1364
           Hospital &amp; Health Care          23713
           Pharmaceuticals                      8054
           Retail                              83950
           Telecommunications                     77
PART       Business Supplies and Equipment       127
           Education Management                 2626
           Hospital &amp; Health Care           4151
           Pharmaceuticals                       121
           Retail                             193981
Name: Industry, dtype: int64

In [26]:
df_temp_cat = df_temp.dropna(subset=['Category'])

df_temp_cat_full = df_temp_cat[df_temp_cat['Category'].str.contains('Full-Time')]
df_temp_cat_full.shape

(122070, 7)

In [27]:
df_temp_cat_part = df_temp_cat[df_temp_cat['Category'].str.contains('Part-Time')]
df_temp_cat_part.shape

(201006, 7)

In [21]:
df_temp_2018 = df_temp[df_temp['Date'].dt.year==2018]
df_temp_2018

,Title,Brand,Category,City,State,Date,Industry
0,Automotive Technician Coggin Honda St. Augustine,Asbury Automotive Group,NaN,St. Augustine,FL,2018-04-12,Automotive
1,Part Time Receptionist / Nights and Weekends /...,Asbury Automotive Group,NaN,Atlanta,GA,2018-03-05,Automotive
2,Service Technician & Used Technician McDavid P...,Asbury Automotive Group,NaN,Plano,TX,2018-04-16,Automotive
3,Part-time Receptionist / Plaza Land Rover,Asbury Automotive Group,NaN,Creve Coeur,MO,2018-04-23,Automotive
4,Automotive Service Technician McDavid Honda Ir...,Asbury Automotive Group,NaN,Irving,TX,2018-04-30,Automotive
5,Sales Consultant / Nalley Honda,Asbury Automotive Group,NaN,Union City,GA,2018-04-25,Automotive
6,Quick Lube Technician McDavid Honda Frisco Int...,Asbury Automotive Group,NaN,Frisco,TX,2018-04-03,Automotive
7,Sales Consultant at Crown Ford Fayetteville,Asbury Automotive Group,NaN,Fayetteville,NC,2018-04-05,Automotive
8,Body Shop Estimator / Toyota of Roswell,Asbury Automotive Group,NaN,Roswell,GA,2018-03-06,Automotive
9,Sales Manager / Nalley Infiniti Atlanta,Asbury Automotive Group,NaN,Atlanta,GA,2018-04-25,Automotive
10,Service Porter / Service Valet / Nalley Ford,Asbury Automotive Group,NaN,Atlanta,GA,2018-04-23,Automotive
11,Sales Consultant / Jaguar Porsche Land Rover &...,Asbury Automotive Group,NaN,Greenville,SC,2018-04-09,Automotive
12,Sales Advisor at Crown CDJR Greensboro,Asbury Automotive Group,NaN,Greensboro,NC,2018-04-13,Automotive
13,Sr. Development Engineer -L3,Bruker,Regular Full-Time,Santa Barbara,CA,2018-02-20,Business Supplies and Equipment
14,MALDI Biotyper Specialist,Bruker,Regular Full-Time,Dallas,TX,2018-03-26,Business Supplies and Equipment
15,HR Generalist,Bruker,Regular Full-Time,Carteret,NJ,2018-04-03,Business Supplies and Equipment
16,Internal Audit Intern,Bruker,Intern Full Time,Billerica,MA,2018-04-05,Business Supplies and Equipment
17,Sales Specialist - Bruker BioSpin Services & L...,Bruker,Regular Full-Time,Chicago,IL,2018-04-17,Business Supplies and Equipment
18,Field Microbiology Application Specialist,Bruker,Regular Full-Time,Seattle,WA,2018-03-19,Business Supplies and Equipment
19,Bruker Applied Spectroscopy Sales Representati...,Bruker,Regular Full-Time,Sacramento,CA,2018-03-29,Business Supplies and Equipment
20,Market Segment Manager BNA Worldwide,Bruker,Regular Full-Time,Madison,WI,2018-04-05,Business Supplies and Equipment
21,Part-Time Temporary Maintenance Mechanic,Bruker,Temporary Part-Time,Carteret,NJ,2018-04-19,Business Supplies and Equipment
23,Staff Software Engineer,Bruker,Regular Full-Time,Santa Barbara,CA,2018-03-14,Business Supplies and Equipment
24,Internal Controls Intern,Bruker,Intern Full Time,Billerica,MA,2018-04-05,Business Supplies and Equipment
25,Buyer - Temp,Bruker,Temporary Part-Time,Tucson,AZ,2018-04-10,Business Supplies and Equipment
26,Quality Control Intern - NI,Bruker,Intern Full Time,Minneapolis,MN,2018-04-24,Business Supplies and Equipment
27,FM -Sr. Staff Manufacturing Engineer - Microscopy,Bruker,Regular Full-Time,Middleton,WI,2018-01-10,Business Supplies and Equipment
28,Mechanical Engineer - Intern,Bruker,Intern Full Time,Santa Barbara,CA,2018-04-25,Business Supplies and Equipment
29,Material Handler,Bruker,Regular Full-Time,Tucson,AZ,2018-04-09,Business Supplies and Equipment
30,BNS- NI Product Line Manager (PLM) of MP,Bruker,Regular Full-Time,Minneapolis,MN,2018-02-27,Business Supplies and Equipment
...,...,...,...,...,...,...,...
12421377,ASIC Verification Engineer,Google,NaN,Mountain View,CA,2018-07-16,Internet
12421429,Communications Manager,Google,NaN,Washington,DC,2018-07-13,Internet
12421553,People Consultant,Google,NaN,Austin,TX,2018-07-18,Internet
12421598,Associate Channels Lead,Google,NaN,Austin,TX,2018-07-12,Internet
12421603,Data Center Technician,Google,NaN,Pryor,OK,2018-07-15,Internet
12421605,Interaction Designer,Google,NaN,Pittsburgh,PA,2018-07-12,Internet
12421608,Systems Planning and Delivery Program Manager,Google,NaN,Sunnyvale,CA,2018-07-19,Internet
12421680,Bay Area Events Program Manager,Google,NaN,Sunnyvale,CA,2018-07-11,Internet
12421682,Data Center Electrical Engineer,Google,NaN,Council Bluffs,IA,2018-07-19,Internet
12421718,Associate Channels Lead,Google,NaN,Mountain View,CA,2018-07-12,Internet
12421725,Interaction Designer,Google,NaN,New York,NY,2018-07-12,Internet
12421728,Data Center Construction Program Manager - Cou...,Google,NaN,Council Bluffs,IA,2018-07-19,Internet
12421788,Test Engineer,Google,NaN,Boulder,CO,2018-07-20,Internet
12421836,Silicon Reliability Test Engineer,Google,NaN,Mountain View,CA,2018-07-19,Internet
12422547,Data Engineer,Pluralsight,4 G&A - Data,South Jordan,UT,2018-06-07,Information Technology and Services
12425437,Senior Manufacturing Engineer - Machining,Waters Corporation,Production and Manufacturing,MA,Milford,2018-02-23,Research
12425445,Principal Systems Specialist,Waters Corporation,Field Service,not set,not set,2018-06-29,Research
12425482,Field Sales Account Manager,Waters Corporation,Field Sales,MA,Milford,2018-05-16,Research
12425486,Senior Service Support and Development Engineer,Waters Corporation,Field Support,MA,Milford,2018-06-07,Research
12425498,Informatics Solutions Specialist,Waters Corporation,Field Service,MA,Milford,2018-05-03,Research
12425511,Material Handler II,Waters Corporation,Transportation Handling,MA,Milford,2018-06-12,Research
12425608,Field Sales Account Manager,Waters Corporation,Field Sales,MA,Milford,2018-05-17,Research
12427236,Project Manager - Project/Program,MAXIMUS,Programme Management,IL,Chicago,2018-07-05,Government Administration
12427241,Operations Manager,MAXIMUS,Operations Management,NY,Queens,2018-06-11,Government Administration
12427341,Project Director,MAXIMUS,Project Manager,NY,Queens,2018-06-11,Government Administration
12428515,Analyst - Operations,MAXIMUS,Analyst,IL,Chicago,2018-07-17,Government Administration
12428556,Project Director,MAXIMUS,Project Manager,NY,Queens,2018-06-11,Government Administration
12428589,Operations Manager,MAXIMUS,Operations Management,NY,Queens,2018-06-11,Government Administration
12428612,Analyst - Operations,MAXIMUS,Analyst,IL,Chicago,2018-07-17,Government Administration
12428638,Project Manager - Project/Program,MAXIMUS,Programme Management,IL,Chicago,2018-07-05,Government Administration

In [22]:
df_temp_2017 = df_temp[df_temp['Date'].dt.year==2017]
df_temp_2017

,Title,Brand,Category,City,State,Date,Industry
22,Sr. Staff Optical Engineer,Bruker,Regular Full-Time,San Jose,CA,2017-06-15,Business Supplies and Equipment
39,Development Engineer -L3,Bruker,Regular Full-Time,Santa Barbara,CA,2017-06-15,Business Supplies and Equipment
46,Product Marketing Applications Engineer - BSEM...,Bruker,Regular Full-Time,Santa Barbara,CA,2017-06-13,Business Supplies and Equipment
50,Maintenance Mechanic (Team D),Bruker,Regular Full-Time,Carteret,NJ,2017-12-06,Business Supplies and Equipment
54,Mechanical Engineer - FM,Bruker,Regular Full-Time,Middleton,WI,2017-12-19,Business Supplies and Equipment
55,Sr. Manufacturing Engineer,Bruker,Regular Full-Time,Santa Barbara,CA,2017-10-30,Business Supplies and Equipment
430,Senior IT Systems Engineer,Pandora,Technical Operations,Oakland,CA,2017-09-28,Internet
446,Sr. IT Systems Engineer,Pandora,Technical Operations,Oakland,CA,2017-09-28,Internet
945,Visiting Professor I - Finance,Adtalem Global Education,Temporary Part-Time,Arlington,VA,2017-11-07,Education Management
962,Visiting Professor - Marketing,Adtalem Global Education,Temporary Part-Time,Arlington,VA,2017-05-08,Education Management
971,Student Support Advisor I DVU,Adtalem Global Education,Regular Full-Time,Naperville,IL,2017-04-27,Education Management
1007,Visiting Professor I - Political Science,Adtalem Global Education,Temporary Part-Time,Arlington,VA,2017-08-29,Education Management
1010,Visiting Professor - Cisco,Adtalem Global Education,Temporary Part-Time,Cleveland,OH,2017-04-25,Education Management
1021,Visiting Professor - Accounting,Adtalem Global Education,Temporary Part-Time,Arlington,VA,2017-06-23,Education Management
1025,Visiting Professor (Part Time) ¡V Anatomy & Ph...,Adtalem Global Education,Temporary Part-Time,Tinley Park,IL,2017-04-11,Education Management
1033,Visiting Professor - Project Management,Adtalem Global Education,Temporary Part-Time,New York,NY,2017-04-20,Education Management
3259,iOS and MacOS SW Application Project Manager,Apple,Software Engineering,Santa Clara Valley,NaN,2017-05-15,Consumer Electronics
3263,CPU Performance Engineer- Austin,Apple,Hardware Engineering,Austin,NaN,2017-06-29,Consumer Electronics
3275,Graphics Verification Engineer,Apple,Hardware Engineering,Santa Clara Valley,NaN,2017-04-18,Consumer Electronics
3277,Sensing System Characterization Engineer,Apple,Hardware Engineering,Santa Clara Valley,NaN,2017-02-14,Consumer Electronics
3279,Engineering Program Manager - Test and Instrum...,Apple,Hardware Engineering,Santa Clara Valley,NaN,2017-02-23,Consumer Electronics
3285,Sr. DFT Design Verification Engineer,Apple,Hardware Engineering,Austin,NaN,2017-05-30,Consumer Electronics
3286,Part TIme Reseller Specialist - West Lebanon,Apple,Sales,West Lebanon,NaN,2017-06-24,Consumer Electronics
3305,RTL Integration Engineer,Apple,Hardware Engineering,Austin,NaN,2017-06-13,Consumer Electronics
3311,Product-Module Packaging Engineer,Apple,Hardware Engineering,Santa Clara Valley,NaN,2017-05-30,Consumer Electronics
3314,Optical Engineer,Apple,Hardware Engineering,Santa Clara Valley,NaN,2017-05-22,Consumer Electronics
3322,Graphics RTL Engineer,Apple,Hardware Engineering,Austin,NaN,2017-06-19,Consumer Electronics
3324,SOC Power CAD engineer,Apple,Hardware Engineering,Santa Clara Valley,NaN,2017-02-21,Consumer Electronics
3335,WW Accessories Channel Offers Specialist,Apple,Sales,Santa Clara Valley,NaN,2017-04-07,Consumer Electronics
3341,Sensor Design Engineer (EE),Apple,Hardware Engineering,Santa Clara Valley,NaN,2017-02-02,Consumer Electronics
...,...,...,...,...,...,...,...
12416206,Restaurant Team Member,Jack in the Box,Restaurant Crew,Riverside,CA,2017-10-11,Restaurants
12416208,Restaurant Team Leader,Jack in the Box,Restaurant Crew,Dallas,TX,2017-10-08,Restaurants
12416424,Restaurant Team Member,Jack in the Box,Restaurant Crew,Los Angeles,CA,2017-10-14,Restaurants
12416436,Restaurant Manager,Jack in the Box,Restaurant Management,San Diego,CA,2017-12-19,Restaurants
12416441,Restaurant Assistant Manager,Jack in the Box,Restaurant Management,Fort Worth,TX,2017-10-27,Restaurants
12416445,Restaurant Team Member,Jack in the Box,Restaurant Crew,Moreno Valley,CA,2017-10-11,Restaurants
12416446,Restaurant Team Member,Jack in the Box,Restaurant Crew,San Diego,CA,2017-10-25,Restaurants
12416450,Restaurant Assistant Manager,Jack in the Box,Restaurant Management,National City,CA,2017-12-19,Restaurants
12416457,Restaurant Team Member,Jack in the Box,Restaurant Crew,Perris,CA,2017-11-10,Restaurants
12416461,Restaurant Team Member,Jack in the Box,Restaurant Crew,National City,CA,2017-10-25,Restaurants
12416470,Restaurant Manager,Jack in the Box,Restaurant Management,San Diego,CA,2017-10-25,Restaurants
12416475,Restaurant Team Member,Jack in the Box,Restaurant Crew,Fort Worth,TX,2017-12-12,Restaurants
12416493,Restaurant Team Leader,Jack in the Box,Restaurant Crew,San Diego,CA,2017-10-25,Restaurants
12416498,Restaurant Manager,Jack in the Box,Restaurant Management,National City,CA,2017-10-25,Restaurants
12416504,Restaurant Manager,Jack in the Box,Restaurant Management,San Diego,CA,2017-12-19,Restaurants
12416505,Restaurant Team Member,Jack in the Box,Restaurant Crew,Riverside,CA,2017-12-05,Restaurants
12416837,Restaurant Team Member,Jack in the Box,Restaurant Crew,Farmers Branch,TX,2017-10-28,Restaurants
12416840,Restaurant Assistant Manager,Jack in the Box,Restaurant Management,San Diego,CA,2017-12-19,Restaurants
12416849,Restaurant Manager,Jack in the Box,Restaurant Management,Fort Worth,TX,2017-10-27,Restaurants
12416850,Restaurant Team Member,Jack in the Box,Restaurant Crew,Temecula,CA,2017-12-14,Restaurants
12416869,Restaurant Manager,Jack in the Box,Restaurant Management,San Diego,CA,2017-12-19,Restaurants
12416875,Restaurant Team Member,Jack in the Box,Restaurant Crew,Rialto,CA,2017-10-11,Restaurants
12416880,Restaurant Assistant Manager,Jack in the Box,Restaurant Management,Farmers Branch,TX,2017-10-28,Restaurants
12416882,Restaurant Team Member,Jack in the Box,Restaurant Crew,Perris,CA,2017-12-14,Restaurants
12416888,Restaurant Manager,Jack in the Box,Restaurant Management,San Diego,CA,2017-12-19,Restaurants
12417242,Restaurant Assistant Manager,Jack in the Box,Restaurant Management,San Diego,CA,2017-12-19,Restaurants
12417251,Restaurant Team Member,Jack in the Box,Restaurant Crew,Fort Worth,TX,2017-10-29,Restaurants
12417254,Restaurant Team Member,Jack in the Box,Restaurant Crew,Hurst,TX,2017-11-02,Restaurants
12417270,Restaurant Assistant Manager,Jack in the Box,Restaurant Management,Dallas,TX,2017-10-27,Restaurants
12417273,Restaurant Manager,Jack in the Box,Restaurant Management,National City,CA,2017-10-25,Restaurants

In [12]:
df.groupby(['State','Industry'])['Industry'].count()

State               Industry
AK                  Apparel & Fashion                         75
                    Business Supplies and Equipment          963
                    Retail                                    33
AL                  Apparel & Fashion                         96
                    Banking                                  594
                    Biotechnology                              3
                    Broadcast Media                          262
                    Building Materials                        88
                    Business Supplies and Equipment         4435
                    Chemicals                                145
                    Construction                             144
                    Defense &amp; Space                      762
                    Electrical/Electronic Manufacturing     1761
                    Internet                                 144
                    Logistics and Supply Chain                82
                    Pharmaceuticals                           18
                    Retail                                 30278
AR                  Apparel & Fashion                         54
                    Banking                                 2137
                    Broadcast Media                          380
                    Business Supplies and Equipment         2206
                    Computer Software                         17
                    Defense &amp; Space                     1004
                    Hospital & Health Care                     6
                    Information Technology and Services      223
                    Internet                                  28
                    Machinery                                 10
                    Retail                                 12174
AZ                  Airlines/Aviation                         40
                    Apparel & Fashion                        542
                                                           ...
WI                  Packaging and Containers                  11
                    Pharmaceuticals                         1733
                    Renewables & Environment                  92
                    Retail                                  4619
WV                  Airlines/Aviation                         35
                    Banking                                 2114
                    Business Supplies and Equipment          524
                    Internet                                  22
                    Retail                                  2586
WY                  Airlines/Aviation                         55
                    Business Supplies and Equipment          460
                    Retail                                  1140
Wake Forest         Real Estate                                3
Wappingers Falls    Real Estate                                3
Warrington          Real Estate                                8
Warsaw              Retail                                     3
Watford City        Oil &amp; Energy                          27
West Palm Beach     Real Estate                                3
Westborough         Real Estate                                9
Westworth Village   Real Estate                                2
Whitehouse Station  Real Estate                                3
Williston           Oil &amp; Energy                          60
Wilmington          Retail                                     3
Winter Garden       Real Estate                                1
Wixom               Real Estate                                3
Woodinville         Retail                                     3
Woodstock           Retail                                     3
Worcester           Retail                                     1
Yardley             Real Estate                                3
not set             Research                                  10
Name: Industry, Length: 989, dtype: int64

In [ ]:
df.groupby(['City','Category']).count()

In [ ]:
website_url = requests.get('https://www.governing.com/gov-data/population-density-land-area-cities-map.html').text

In [ ]:
# get the table
soup = BeautifulSoup(website_url,'lxml')
my_table = soup.find("table", { "class":"dataTable"})

In [ ]:
# Function: Convert BeautifulSoup tags to string list
def convert_to_list(bs4row):
    list_bs4row = bs4row.findAll(["td","th"])
    return [bs4.get_text().strip() for bs4 in list_bs4row]

In [ ]:
# get the table
soup = BeautifulSoup(website_url,'lxml')
my_table = soup.find("table", { "class":"dataTable"})
rows=my_table.findAll("tr")

# convert to list of list
my_data = [convert_to_list(r) for r in rows[1:]]

In [ ]:
df_city = pd.DataFrame(my_data,columns=['City,State','Population_Density','Population','Land_Area'])

# convert the number from string to integer
for col in df_city.columns[1:]:
    df_city[col]=df_city[col].apply(lambda s: int(s.replace(',','')))

In [ ]:
US_city = [city.upper().split(",")[0] for city in df_city['City,State'].tolist()]
US_city

In [ ]:
df_US_city = df[df['City'].str.upper().isin(US_city)]

In [ ]:
df_US_city.shape[0]

In [ ]:
df_US_city.groupby(['City','Category'])['Title'].count()

In [ ]:
df['Date'].min()

In [ ]:
df['Date'].max()

In [ ]:
df_state = pd.read_csv('WebScraping_state_abv.csv')

In [ ]:
state_abv = dict(zip(df_state['Full_name'].tolist(),df_state['USPS'].tolist()))

In [ ]:
state_abv

In [ ]:
df['Brand']